"""
IntentCart - Phase L9/L10 Verification Test
Script: tests/test_grounded_explanation.py

Tests the GroundedExplainer module on real ML pipeline output:
Verifies that:
1. Hard constraint enforcement is acknowledged
2. Explanations cite only real attributes from candidate evidence
3. Output is warm, conversational, and completely grounded
"""

import sys
import os

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from llm.intent_extractor import intent_extractor
from llm.adapter import map_schema_to_pipeline_args
from retrieval.pipeline import IntentCartPipeline
from llm.explainer import grounded_explainer

def test_explainer():
    print("=" * 70)
    print(" IntentCart - Grounded Conversational Explanation Test")
    print("=" * 70)

    user_query = (
        "I need a wedding-day kurta for my brother's wedding, comfortable and minimal, "
        "no floral patterns, formal and breathable for summer."
    )

    print(f"\nUser Query: \"{user_query}\"")

    # 1. Extract intent
    schema, _ = intent_extractor.extract_intent(user_query)
    pipeline_kwargs = map_schema_to_pipeline_args(schema)

    # 2. Run ML Pipeline
    pipeline = IntentCartPipeline()
    output = pipeline.run(**pipeline_kwargs, top_k=3)

    # 3. Generate Grounded Explanation
    print("\nGenerating grounded conversational explanation via LLMRouter...")
    explanation, meta = grounded_explainer.explain_recommendations(
        user_query=user_query,
        hard_constraints=pipeline_kwargs["hard_constraints"],
        soft_intent=pipeline_kwargs["soft_intent"],
        pipeline_output=output
    )

    print("-" * 70)
    print(f"Explanation Generated by: {meta.get('provider').upper()} ({meta.get('model')}) in {meta.get('latency_ms')} ms")
    print("-" * 70)
    print(explanation)
    print("-" * 70)

if __name__ == "__main__":
    test_explainer()
